### ISSUE TITLE
Indenting after an if - inside a function.

### ISSUE THREAD

**Issue by merlinblack** [2072/PHP-Indenting-for-VIm#45] opened 2015-06-10 04:15 UTC
I've just installed your script to try and fix a recent problem with the default vim script installed on Fedora 22.  It did not fix it - however I'm not sure if it is a problem in both or that your script does not override the wrong behaviour.  I've confirmed your script is being loaded using 'vim -D'.

The problem does not appear at file scope level.  Inside a function it does.

    function test() {
        if( expr ) {
            dosomething();
        }
            // Indent after the closing brace is one too many.
    }

I'm thinking it is probably a problem with the version in Fedora 22, and your script doesn't fix it.  Otherwise surely someone else would have mentioned it here!  Just a stab in the dark though.

Thanks! :-)

**Comment by 2072** [comment] 2015-06-13 23:11
I can't reproduce this. Make sure that `g:PHP_outdentSLComments` global variable is not set as it specifically adds indentation to single line comments. If it's set to 1 type `:let b:PHP_outdentSLComments=0` and test indentation again.

**Comment by merlinblack** [comment] 2015-06-15 04:28
Thank you for looking at this.  That global variable is undefined however it's not just comments that get indented more than they should - that's just what I used as an example.
What system did you try it on? I'm becoming fairly certain this is a Fedora 22 only problem.

Thanks again.

**Comment by 2072** [comment] 2015-06-15 17:06
I tested on Windows 7 and Debian Jessie. You should check that the indent function used is the right one.

Type the command `:verbose function GetPhpIndent`

**Comment by merlinblack** [comment] 2015-06-17 07:32
The second or so line of output from the command you suggested said:
" Last set from ~/.vim/bundle/PHP-Indenting-for-VIm/indent/php.vim"

So it looks like it is loading correctly and that is the one it is running.

I'll see if I can replicate it on my Mac.  I'm fairly sure I have an Ubuntu vagrant box still too I could test on.

**Comment by villainy** [comment] 2015-07-16 19:36
This has been driving me nuts in Fedora 22 and happens with stock or git versions of this indent plugin. F22 shipped version of vim is 7.4.640.

Could not reproduce with git version in CentOS 7 vim 7.4.160 or Cygwin vim 7.4.729. Seems specific to something going on in F22 :(

**Comment by 2072** [comment] 2015-07-17 18:35
What is the syntax file being used for PHP in F22? The indent script depends on it.

**Comment by villainy** [comment] 2015-07-17 22:47
MD5 matches between the F22 and Cent 7 syntax files at /usr/share/vim/vim74/syntax/php.vim. I don't see a specific version noted but the header comments include:

```
" Vim syntax file
" Language: php PHP 3/4/5
" Maintainer: Jason Woofenden <jason@jasonwoof.com>
" Last Change: Dec 11, 2012
" URL: https://gitorious.org/jasonwoof/vim-syntax/blobs/master/php.vim
" Former Maintainers: Peter Hodge <toomuchphp-vim@yahoo.com>
"         Debian VIM Maintainers <pkg-vim-maintainers@lists.alioth.debian.org>
```

**Comment by 2072** [comment] 2015-08-01 19:34
Could you try to compile VIM from the current source (from the official Hg repository)?  Maybe the problem was introduced between 7.4.160 and 7.4.640 but is fixed in 7.4.729...

**Comment by villainy** [comment] 2015-08-02 05:27
Rebuilt F22's 640 RPM patched up to 803 and the problem went away. Downgraded back to 640 and the problem reappeared. Looks like it was indeed fixed somewhere along the way. Thanks for the suggestion!

Looks like there's a copr with 803 too:
https://copr.fedoraproject.org/coprs/lantw44/vim-latest/

**Comment by merlinblack** [comment] 2015-08-02 18:22
I've tried the latest source too - and indeed the problem is gone! Awesome!

**Closed** 2015-09-06 22:08 UTC
